#version 460

#define _X	(800/25)
#define _Y	(800/25)

layout (local_size_x = _X, local_size_y = _Y) in;

//layout (set = 0, binding = 1, rgba8ui) uniform writeonly uimageBuffer dstObj;

layout (set = 0, binding = 0, rgba8) uniform readonly highp image2D srcObj;
layout (set = 0, binding = 1, rgba8) uniform writeonly imageBuffer dstObj;

void main() {
	ivec2 pos2d = ivec2(gl_GlobalInvocationID.xy);
	int pos1d = pos2d.y * 800 + pos2d.x;
	imageStore(dstObj, pos1d, imageLoad(srcObj, pos2d));
}
